# Generated by Django 5.2 on 2026-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('left_stick_x', models.FloatField(default=0.0)),
                ('left_stick_y', models.FloatField(default=0.0)),
                ('right_stick_x', models.FloatField(default=0.0)),
                ('right_stick_y', models.FloatField(default=0.0)),
                ('button_a', models.BooleanField(default=False)),
                ('button_b', models.BooleanField(default=False)),
                ('button_x', models.BooleanField(default=False)),
                ('button_y', models.BooleanField(default=False)),
                ('left_bumper', models.BooleanField(default=False)),
                ('right_bumper', models.BooleanField(default=False)),
                ('left_trigger', models.FloatField(default=0.0)),
                ('right_trigger', models.FloatField(default=0.0)),
                ('back_select', models.BooleanField(default=False)),
                ('start_menu', models.BooleanField(default=False)),
                ('left_stick_press', models.BooleanField(default=False)),
                ('right_stick_press', models.BooleanField(default=False)),
                ('dpad_up', models.BooleanField(default=False)),
                ('dpad_down', models.BooleanField(default=False)),
                ('dpad_left', models.BooleanField(default=False)),
                ('dpad_right', models.BooleanField(default=False)),
                ('xbox_home', models.BooleanField(default=False)),
            ],
        ),
    ]
